baseURL = "http://www.chillu.com"
title = "Ingo Schommer"
theme = "hugo-coder"

[params]
author = "Ingo Schommer"
description = "Ingo Schommer's personal website"
keywords = "blog,developer,personal"
info = ["Passionate about product, people and data." ]
avatarURL = "images/avatar.jpg"
footerContent = "<a href=\"mailto:me@chillu.com\">Contact</a>"
since = 2005
colorScheme = "dark"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive â€“ defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/chillu/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/chillu/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/ingoschommer/"


[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 6
url = "https://chillu.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

#[[languages.en.menu.main]]
#name = "About"
#weight = 1
#url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"